version: 0.2
phases:
  build:
    commands:
    - echo Build started
    - mvn clean package
  post_build:
    commands:
    - echo Build completed successfully
artifacts:
  discard-paths: yes
  files:
  - target/cricshine.war